name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3.6.0
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2.2.2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-pkg-config
          
    - name: Build
      shell: msys2 {0}
      run: |
        gcc sorter.c -o sorter.exe `pkg-config --cflags --libs gtk+-3.0` -mwindows
        
    - name: Copy DLLs
      shell: msys2 {0}
      run: |
        mkdir dist
        cp sorter.exe dist/
        ldd sorter.exe | grep -i mingw | awk '{print $3}' | xargs -I{} cp {} dist/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: windows-build
        path: dist/